// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerAppBlazor.Database;

#nullable disable

namespace PlayerAppBlazor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127054815_ConvertDiceTypeToEnum2")]
    partial class ConvertDiceTypeToEnum2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("PlayerApp.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterRaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mana")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.HasIndex("CharacterRaceId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HitDice")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVeteranLocked")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManaDice")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CharacterClasses");
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RaceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CharacterRaces");
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterStatBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BonusSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BonusValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelectable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterStatBonus");
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wisdom")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterStats");
                });

            modelBuilder.Entity("PlayerApp.Models.Modifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Modifiers");
                });

            modelBuilder.Entity("PlayerApp.Models.RaceStatBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusValue")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterRaceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelectable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterRaceId");

                    b.ToTable("RaceStatBonus");
                });

            modelBuilder.Entity("PlayerApp.Models.RacialModifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModifierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RaceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModifierId");

                    b.HasIndex("RaceId");

                    b.ToTable("RacialModifiers");
                });

            modelBuilder.Entity("PlayerApp.Models.Character", b =>
                {
                    b.HasOne("PlayerApp.Models.CharacterClass", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId");

                    b.HasOne("PlayerApp.Models.CharacterRace", "CharacterRace")
                        .WithMany()
                        .HasForeignKey("CharacterRaceId");

                    b.Navigation("CharacterClass");

                    b.Navigation("CharacterRace");
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterStatBonus", b =>
                {
                    b.HasOne("PlayerApp.Models.Character", null)
                        .WithMany("CharacterStatBonuses")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterStats", b =>
                {
                    b.HasOne("PlayerApp.Models.Character", "Character")
                        .WithOne("Stats")
                        .HasForeignKey("PlayerApp.Models.CharacterStats", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PlayerApp.Models.RaceStatBonus", b =>
                {
                    b.HasOne("PlayerApp.Models.CharacterRace", null)
                        .WithMany("RaceStatBonuses")
                        .HasForeignKey("CharacterRaceId");
                });

            modelBuilder.Entity("PlayerApp.Models.RacialModifier", b =>
                {
                    b.HasOne("PlayerApp.Models.Modifier", "Modifier")
                        .WithMany("RacialModifiers")
                        .HasForeignKey("ModifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerApp.Models.CharacterRace", "Race")
                        .WithMany("Modifiers")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modifier");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("PlayerApp.Models.Character", b =>
                {
                    b.Navigation("CharacterStatBonuses");

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterRace", b =>
                {
                    b.Navigation("Modifiers");

                    b.Navigation("RaceStatBonuses");
                });

            modelBuilder.Entity("PlayerApp.Models.Modifier", b =>
                {
                    b.Navigation("RacialModifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
