// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerAppAvalonia.Database;

#nullable disable

namespace PlayerAppAvalonia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayerApp.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacterClassId")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterRaceId")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("Mana")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.HasIndex("CharacterRaceId");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HitDiceId")
                        .HasColumnType("int");

                    b.Property<int>("ManaDiceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HitDiceId");

                    b.HasIndex("ManaDiceId");

                    b.ToTable("CharacterClass");
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CharacterRace");
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterStats");
                });

            modelBuilder.Entity("PlayerApp.Models.DiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sides")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "D4",
                            Sides = 4
                        },
                        new
                        {
                            Id = 2,
                            Name = "D6",
                            Sides = 6
                        },
                        new
                        {
                            Id = 3,
                            Name = "D8",
                            Sides = 8
                        },
                        new
                        {
                            Id = 4,
                            Name = "D10",
                            Sides = 10
                        },
                        new
                        {
                            Id = 5,
                            Name = "D12",
                            Sides = 12
                        },
                        new
                        {
                            Id = 6,
                            Name = "D20",
                            Sides = 20
                        });
                });

            modelBuilder.Entity("PlayerApp.Models.Modifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Modifiers");
                });

            modelBuilder.Entity("PlayerApp.Models.RacialModifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModifierId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModifierId");

                    b.HasIndex("RaceId");

                    b.ToTable("RacialModifiers");
                });

            modelBuilder.Entity("PlayerApp.Models.Character", b =>
                {
                    b.HasOne("PlayerApp.Models.CharacterClass", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId");

                    b.HasOne("PlayerApp.Models.CharacterRace", "CharacterRace")
                        .WithMany()
                        .HasForeignKey("CharacterRaceId");

                    b.Navigation("CharacterClass");

                    b.Navigation("CharacterRace");
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterClass", b =>
                {
                    b.HasOne("PlayerApp.Models.DiceType", "HitDice")
                        .WithMany()
                        .HasForeignKey("HitDiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PlayerApp.Models.DiceType", "ManaDice")
                        .WithMany()
                        .HasForeignKey("ManaDiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HitDice");

                    b.Navigation("ManaDice");
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterStats", b =>
                {
                    b.HasOne("PlayerApp.Models.Character", "Character")
                        .WithOne("Stats")
                        .HasForeignKey("PlayerApp.Models.CharacterStats", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("PlayerApp.Models.RacialModifier", b =>
                {
                    b.HasOne("PlayerApp.Models.Modifier", "Modifier")
                        .WithMany("RacialModifiers")
                        .HasForeignKey("ModifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlayerApp.Models.CharacterRace", "Race")
                        .WithMany("Modifiers")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modifier");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("PlayerApp.Models.Character", b =>
                {
                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("PlayerApp.Models.CharacterRace", b =>
                {
                    b.Navigation("Modifiers");
                });

            modelBuilder.Entity("PlayerApp.Models.Modifier", b =>
                {
                    b.Navigation("RacialModifiers");
                });
#pragma warning restore 612, 618
        }
    }
}
